
name: update-bundle-images

on: [push, workflow_dispatch]

  # Triggers the workflow every 1 minutes
  #schedule:
  #  - cron: "*/1 * * * *"

jobs:
  obtain-trivy-image-tags:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      TAGS_TO_FETCH: 3
      NO_IMAGE_FLAG: "No Trivy Image Found"

    steps:
      - uses: actions/checkout@v3
        with:
          repository: mesosphere/dkp-insights
          ref: main
          submodules: 'false'
          token: ${{ secrets.MERGEBOT_TOKEN }}

      - run: mkdir -p artifacts && touch ./artifacts/tags-to-rebuild.txt
      - run: git fetch --all --tags
      - run: |
          dkp_insights_tags=($(git tag | tail -n $TAGS_TO_FETCH))

          for tag in "${dkp_insights_tags[@]}"
          do
            git checkout ${tag}

            trivy_image_tag=$(cat ./charts/dkp-insights/values.yaml | grep -o 'mesosphere/trivy-bundles:.*' | cut -f2- -d: || echo $NO_IMAGE_FLAG)

            if [ "$trivy_image_tag" != "$NO_IMAGE_FLAG" ]; then
              if [[ ! " ${trivy_image_tags[*]} " =~ " ${trivy_image_tag} " ]]; then
                echo "$trivy_image_tag" >> ./artifacts/tags-to-rebuild.txt
              fi
            fi

          done

      - uses: actions/upload-artifact@v3
        with:
          name: trivy-tags-to-rebuild
          path: ./artifacts/tags-to-rebuild.txt

  rebuild-trivy-bundle-images:
    needs: [obtain-trivy-image-tags]

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: trivy-tags-to-rebuild
      - run: ls
