
name: update-bundle-images

on:
  push:
  workflow_dispatch:
  schedule:
    # at 6  a.m. every Wednesday
    - cron: "0 6 * * 3"

env:
  TAGS_TO_FETCH: 2
  TRIVY_IMAGE_NAME: mesosphere/trivy-bundles

jobs:
  # TODO: add condition to make the job run every OTHER week
  obtain-trivy-image-tags:
    runs-on: ubuntu-latest
    env:
      # leave blank if you don't want to rebuild trivy-bundles image for the main branch
      dkp_insights_main_branch_name: "origin/main"
    steps:
      - name: Clone dkp-insights Repository
        uses: actions/checkout@v3
        with:
          repository: mesosphere/dkp-insights
          ref: main
          submodules: 'false'
          token: ${{ secrets.MERGEBOT_TOKEN }}

      - name: Create Artifact for trivy-bundles Image Tags
        run: mkdir -p artifacts && touch ./artifacts/tags-to-rebuild.txt

      - name: Fetch All Branches from dkp-insights Repository
        run: git fetch

      - name: Obtain trivy-bundles Image Tags for each dkp-insights Release Branch
        run: |
          dkp_insights_release_branches=($(git branch -r | grep 'origin/release' | tail -n $TAGS_TO_FETCH))

          if [[ ! -z "dkp_insights_main_branch_name" ]]; then
            dkp_insights_release_branches+=($dkp_insights_main_branch_name)
          fi

          echo "dkp_insights_release_branches: ${dkp_insights_release_branches[@]}"

          for branch in "${dkp_insights_release_branches[@]}"
          do
            git checkout $branch

            trivy_image_tag=$(cat ./charts/dkp-insights/values.yaml | grep -o 'mesosphere/trivy-bundles:.*' | cut -f2- -d: || :)

            echo $trivy_image_tag

            if [[ ! -z "$trivy_image_tag" ]]; then
              echo "${branch}=${trivy_image_tag}" >> ./artifacts/tags-to-rebuild.txt
            fi

          done

      - name: Upload Artifact with trivy-bundles Image Tags
        uses: actions/upload-artifact@v3
        with:
          name: trivy-tags-to-rebuild
          path: ./artifacts/tags-to-rebuild.txt


  rebuild-trivy-bundles-images:
    needs: [obtain-trivy-image-tags]
    runs-on: ubuntu-latest
    steps:
      - name: Clone trivy-bundles Repository
        uses: actions/checkout@v3
        with:
          repository: mesosphere/trivy-bundles
          ref: main
      
      - name: Download Artifact with dkp-insights Release Branches and their trivy-bundles Image Tags
        uses: actions/download-artifact@v3
        with:
          name: trivy-tags-to-rebuild

      - name: Create an Artifact for Saving Updated trivy-bundles Image Tags
        run: mkdir -p artifacts && touch ./artifacts/updated-trivy-bundles-image-tags.txt
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_READ_WRITE_USERNAME }}
          password: ${{ secrets.DOCKER_READ_WRITE_PASSWORD }}

      - name: Rebuild and Push Updated trivy-bundles Images
        run: |
          while read branch_and_tag; do
            dkp_insights_branch=${branch_and_tag%=*}
            trivy_bundles_image_tag=${branch_and_tag##*=}
            trivy_image_version=${trivy_bundles_image_tag%-*}
            updated_time_stamp=$(date -u +%Y%m%dT%H%M%SZ)

            echo "dkp_insights_branch: $dkp_insights_branch"
            echo "trivy_bundles_image_tag: $trivy_bundles_image_tag"
            echo "trivy_image_version: $trivy_image_version"
            echo "time_stamp: $updated_time_stamp"


            
            echo "${dkp_insights_branch}=${trivy_image_version}-${updated_time_stamp}" >> ./artifacts/updated-trivy-bundles-image-tags.txt

          done <tags-to-rebuild.txt

      
      #   TRIVY_IMAGE_TAG=$trivy_image_version \
      # TIMESTAMP=$updated_time_stamp \
      # OUTPUT_IMAGE=$TRIVY_IMAGE_NAME \
      # make publish-trivy-bundled-image

      - name: Upload Artifact with dkp-insights Release Branch Names and their Corresponding Updated trivy-bundles Image Tags
        uses: actions/upload-artifact@v3
        with:
          name: updated-trivy-bundles-image-tags
          path: ./artifacts/updated-trivy-bundles-image-tags.txt


  update-dkp-insights-release-branches:
    needs: [rebuild-trivy-bundles-images]
    runs-on: ubuntu-latest
    steps:

      - name: Reinstall Go for Current User
        run: |
          wget "https://go.dev/dl/$(curl 'https://go.dev/VERSION?m=text').linux-amd64.tar.gz"
          sudo tar -C /usr/local -xzf go*.linux-amd64.tar.gz

      - name: Create folder for cloning dkp-insights
        run: |
          sudo mkdir dkp-insights
          sudo chmod  -R  0777 ./dkp-insights
      
      - name: Create folder for moving dkp-insights within go path
        run: |
          sudo mkdir -p //usr/local/go/src/github.com/mesosphere/dkp-insights
          sudo chmod  -R  0777 //usr/local/go/src/github.com/mesosphere/dkp-insights

      - name: Clone dkp-insights Repository
        uses: actions/checkout@v3
        with:
          repository: mesosphere/dkp-insights
          ref: main
          submodules: 'true'
          path: dkp-insights
          token: ${{ secrets.MERGEBOT_TOKEN }}

      - name: Move dkp-insights Repository to GOPATH
        run: |
          mv ./dkp-insights/* ./dkp-insights/.[!.]* ./dkp-insights/..?* //usr/local/go/src/github.com/mesosphere/dkp-insights/ || :
          cd //usr/local/go/src/github.com/mesosphere/dkp-insights
          ls -a
          
      - name: Fetch All Branches from dkp-insights Repository
        working-directory: //usr/local/go/src/github.com/mesosphere/dkp-insights
        run: git fetch

      - name: Set Git Global Username and Email
        run: |
          git config --global user.email "ci-mergebot@d2iq.com"
          git config --global user.name "d2iq-mergebot"

      - name: Download Artifact with dkp-insights Release Branches and their Updated trivy-bundles Image Tags
        uses: actions/download-artifact@v3
        with:
          name: updated-trivy-bundles-image-tags
      
      - name: Move updated-trivy-bundles-image-tags artifact to dkp-insights repository
        run: mv updated-trivy-bundles-image-tags.txt //usr/local/go/src/github.com/mesosphere/dkp-insights
      
      - name: Install Hub (wrapper for git for opening PRs)
        run: sudo apt install hub
      
      - name: Update trivy-bundles Image Tags in Each dkp-insights Release Branch and Open a Pull Request
        working-directory: //usr/local/go/src/github.com/mesosphere/dkp-insights
        env:
          GITHUB_TOKEN: ${{ secrets.MERGEBOT_TOKEN }}
        run: |
          echo "setup environment"
          export PATH=$PATH:/usr/local/go/bin
          echo "GOPATH=/usr/local/go" >> ~/.bashrc
          export GOPATH=/usr/local/go
          export IR=${GOPATH}/src/github.com/mesosphere/dkp-insights
          export PATH=${IR}/.local/tools:${PATH}

          while read branch_and_tag; do
            dkp_insights_branch=${branch_and_tag%=*}
            trivy_bundles_image_tag=${branch_and_tag##*=}
            trivy_image_version=${trivy_bundles_image_tag%-*}
            updated_time_stamp=$(date -u +%Y%m%dT%H%M%SZ)

            echo "dkp_insights_branch: $dkp_insights_branch"
            echo "trivy_bundles_image_tag: $trivy_bundles_image_tag"
            echo "trivy_image_version: $trivy_image_version"
            echo "time_stamp: $updated_time_stamp"

            echo "checkout branch"
            dkp_insights_branch_name=$( echo $dkp_insights_branch  | cut -f2- -d/ )
            git checkout -b GHA/update-trivy-bundles-image-in/$dkp_insights_branch_name $dkp_insights_branch

            echo "replace image tag name"
            replace_string=$TRIVY_IMAGE_NAME:$trivy_image_version-$updated_time_stamp
            sed -i "s|$TRIVY_IMAGE_NAME:$trivy_image_version-[0-9]\{8\}T[0-9]\{6\}Z|$replace_string|" ./charts/dkp-insights/values.yaml

            echo "commit and push changes"
            git add ./charts/dkp-insights/values.yaml
            git commit -m "Updating trivy-bundles image on $(date -u +%Y-%m-%d)"
            git push origin GHA/update-trivy-bundles-image-in/$dkp_insights_branch_name

            echo "open a pull request"
            hub pull-request -m "trivy-bundles image automatic update $(date -u +%Y-%m-%d)" \
              --no-edit \
              --base $dkp_insights_branch_name \
              --labels "ok-to-test","ready for review"

          done <updated-trivy-bundles-image-tags.txt
